# Generated by Django 4.2.11 on 2024-04-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_user_delete_kayit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
