# Generated by Django 4.2.11 on 2024-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
