# Generated by Django 4.2.11 on 2024-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(null=True, upload_to='classes/%Y/%m/%d/'),
        ),
    ]
