# Generated by Django 4.2.11 on 2024-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_alter_trainer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='classes/default_indir.jpeg', null=True, upload_to='classes/%Y/%m/%d/'),
        ),
    ]
