# Generated by Django 4.2.11 on 2024-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_trainer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='classes/default_indir.jpeg', upload_to='classes/%Y/%m/%d/'),
        ),
    ]
