# Generated by Django 4.2.11 on 2024-04-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_category_trainer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='Category',
        ),
        migrations.AddField(
            model_name='trainer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainer.category'),
        ),
    ]
