# Generated by Django 4.2.11 on 2024-04-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_remove_trainer_category_trainer_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='category',
            new_name='Category',
        ),
    ]
