# Generated by Django 4.2.11 on 2024-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='trainer.tag'),
        ),
    ]
